### ISSUE TITLE
`Option<T>` not handled properly

### ISSUE THREAD

**Issue by thorlucas** [jakobhellermann/bevy-inspector-egui#10]
It seems that, while we can revert an `Option<T>` back to `None`, there is no way to convert it back to `Some(...)`.

<img width="144" alt="Screen Shot 2021-04-11 at 6 48 18 PM" src="https://user-images.githubusercontent.com/25698466/114330397-7c1f7200-9af6-11eb-9dad-c6dc03e09368.png">

<img width="119" alt="Screen Shot 2021-04-11 at 6 48 27 PM" src="https://user-images.githubusercontent.com/25698466/114330408-817cbc80-9af6-11eb-89a5-ada1538f1b96.png">

Perhaps `Option<T>` should be handled by a checkbox (indicating `None` when off, and `Some` when on), and a textbox that appears to the right of it when on.

**Comment by jakobhellermann** [comment]
The option inspectable can be configured using the [OptionAttributes](https://docs.rs/bevy-inspector-egui/0.4.1/bevy_inspector_egui/options/struct.OptionAttributes.html) which have a `replacement` field.

You can do 
```rust
#[derive(Inspectable)]
struct Data {
    #[inspectable(replacement = option_replacement as fn() -> f32)]
    option: Option<f32>,
    #[inspectable(replacement = String::default as fn() -> String)]
    option2: Option<String>,
}
fn option_replacement() -> f32 {
    0.0
}
```
(the `as fn() -> _` is because of some rustc type inference quirk)

**Comment by thorlucas** [comment]
I somehow missed this in the demo. Thanks!

**Comment by unknownue** [comment]
I found a simple solution to this problem. When dealing with `Option<T>` in bevy-inspector-egui where T is a custom type that implements `Default`, adding `#[reflect(Default)]` attribute to the type T will enable switching from `None` to `Some(T)` in the inspector.

```rust
#[derive(Default, Reflect)]
#[reflect(Default)]
pub enum MyEnum {
    #[default]
    ValueA,
    ValueB,
}
```
