### ISSUE TITLE
Option to split entity list & components

### ISSUE THREAD

**Issue by alyti** [jakobhellermann/bevy-inspector-egui#11]
As titled, I think it might be worth to experiment with layout of the UI, in this case the entities and their relations stay in top half of the window and second half would be dedicated to the components.

**Comment by msklywenn** [comment]
[I implemented that](https://github.com/msklywenn/bevy-inspector-egui) (with two panels though) with a [custom version of egui](https://github.com/msklywenn/egui)

**Comment by jakobhellermann** [comment]
I created <https://github.com/jakobhellermann/bevy_editor_pls> to build a more familiar editor-like UI on top of the inspector, so I think bevy-inspector-egui itself can stay the way it is and bevy_editor_pls can be used for the split layout.

![grafik](https://user-images.githubusercontent.com/22177966/153751363-ecc52d95-d9d6-4fe6-bdd0-413142f1fa91.png)
