### ISSUE TITLE
Problem with tuple structs and WorldInspector

### ISSUE THREAD

**Issue by DanilaMihailov** [jakobhellermann/bevy-inspector-egui#12]
I have a few components defined as tuple structs, and when I try to inspect them it says "Inspectable has not been defined for this component". It works great for anything else tho, great plugin btw :)

Example from my project 

```rust
#[derive(Clone, Inspectable)]
pub struct Health(pub u32);

#[derive(Clone, Inspectable)]
pub struct Damage(pub u32);
```

and here is the screenshot
<img width="562" alt="Screenshot 2021-04-25 at 17 27 38" src="https://user-images.githubusercontent.com/1163040/115993321-b3f4e200-a5eb-11eb-86da-13bc1cf5330c.png">

**Comment by DanilaMihailov** [comment]
I am using `WorldInspectorPlugin`. And I thought if I derive `Inspectable` for my components, I will be able to edit their fields. I actually tried it with another component, which is simple struct and it does not work. Should it work or I just misunderstood something?

Simple component example 
```rust
#[derive(Inspectable, Clone)]
pub struct ColliderBox {
    #[inspectable(min = 0, max = 900)]
    pub w: u32,
    #[inspectable(min = 0, max = 900)]
    pub h: u32,
}
```

**Comment by DanilaMihailov** [comment]
My bad, I had to call `.insert_resource(InspectableRegistry::default().with::<ColliderBox>())` for my component to work. Is this the right thing to do? If so I would gladly add this to `examples/world.rs`, so people like me won't get confused :)

**Comment by jakobhellermann** [comment]
Thank you for the PR.
