### ISSUE TITLE
Smaller fonts / decorations

### ISSUE THREAD

**Issue by Luminoth** [jakobhellermann/bevy-inspector-egui#14]
Not so much an issue - I'm just curious if there is a way to configure the font size and the size of the UI element decorations. I have a window that's 1024x576 and I'd like to be able to fit more of the inspector content into that space if I can.

**Comment by jakobhellermann** [comment]
You can insert a [EguiSettings](https://docs.rs/bevy_egui/0.4.2/bevy_egui/struct.EguiSettings.html) resource:
```rust
app.insert_resource(EguiSettings { scale_factor: 0.8 })
```
This will change the global egui scale.

**Comment by Luminoth** [comment]
Perfect! Thank you.
