### ISSUE TITLE
Read-only and hidden fields

### ISSUE THREAD

**Issue by Luminoth** [jakobhellermann/bevy-inspector-egui#15]
Would it be possible to add options to the Inspectable attributes to make fields in an inspectable struct hidden or read-only?

**Comment by Luminoth** [comment]
Might be a duplicate of #8 but I think with a more directed feature request at having it be part of the inspectable attribute.

**Comment by jakobhellermann** [comment]
For hiding fields in the inspector you can do `#[inspectable(ignore)]`. I should document the attributes more.
Making a field read only could work with a hypothetical `#[inspectable(read_only)]` attribute, although you'd still need mutable access.

A more general solution might be to also provide a `#[inspectable(prepare = set_ui_disabled)]` attribute used with a
```rust
fn set_ui_disabled(ui: &mut egui::Ui) {
  ui.set_enabled();
}
```

**Comment by jakobhellermann** [comment]
I implemented the [`read_only`](https://github.com/jakobhellermann/bevy-inspector-egui/blob/71e9a749fec5ee3ae189791e867e755d10daabcf/examples/rust_types.rs#L22) and [`wrapper`](https://github.com/jakobhellermann/bevy-inspector-egui/blob/71e9a749fec5ee3ae189791e867e755d10daabcf/examples/rust_types.rs#L20) attributes and [documented](https://github.com/jakobhellermann/bevy-inspector-egui/blob/71e9a749fec5ee3ae189791e867e755d10daabcf/src/lib.rs#L179) the built-in attributes.

I'll release a new version containing the changes tomorrow.

**Comment by jakobhellermann** [comment]
`bevy-inspector-egui` 0.5 is out with [the attributes](https://docs.rs/bevy-inspector-egui/0.5.0/bevy_inspector_egui/trait.Inspectable.html#default-attributes). I think this issue is solved now.
