### ISSUE TITLE
Building world example with "dynamic" causes link error "fatal error LNK1189: library limit of 65535 objects exceeded"

### ISSUE THREAD

**Issue by 00alia00** [jakobhellermann/bevy-inspector-egui#17]
At head if i remove "dynamic" from dev-dependencies then it links/runs fine.

**Comment by jakobhellermann** [comment]
Seems to be a case of https://github.com/bevyengine/bevy/issues/1110. I'll remove the dynamic feature for now so that running works on windows without changes.
