### ISSUE TITLE
world example image is out of date

### ISSUE THREAD

**Issue by 00alia00** [jakobhellermann/bevy-inspector-egui#18]
I spent way too long trying to figure out how to add the Generate button in the current screenshot. Couldnt see it anywhere in the source so I have attached newer screenshot.

![image](https://user-images.githubusercontent.com/537506/118714736-96c0c700-b7d7-11eb-90d6-98f31c50dbcf.png)

**Comment by jakobhellermann** [comment]
Thanks, I updated it now.
