### ISSUE TITLE
Transform.rotation is changed visually/incorrectly in the world inspector

### ISSUE THREAD

**Issue by Looooong** [jakobhellermann/bevy-inspector-egui#21]
Modifying `Transform.rotation` of one entity in the world inspector changes visual representation of the `Transform.rotation` of other entity. Although `GlobalTransform.rotation` may change, `Transform.rotation` must not change because it is local to the entity space. Therefore, I think that there is something wrong with the `Transform.rotation` presentation in the world inspector.

Here is a demo video. Notice the other's `Transform.rotation` being changed when changing `Transform.rotation` of an entity.

https://user-images.githubusercontent.com/8206622/122642236-8a5fbf00-d133-11eb-93d5-ccc21b63e151.mp4

**Comment by Weibye** [comment]
I discovered the same issue today:

Changing `Scale` and `Translation` of the Parent `Transform` works correctly. 
Changing `Rotation` of the parent `Transform` results in a change to the child `Transform` instead a change to the `GlobalTransform` as expected.

**Comment by jakobhellermann** [comment]
The issue should be fixed now. Can you try again with the `main` branch? (`bevy-inspector-egui = { git = "https://github.com/jakobhellermann/bevy-inspector-egui", branch = "main" }`

**Comment by Weibye** [comment]
Yup, seems to be fixed on main, thanks!
