### ISSUE TITLE
Controlling InspectorWindows

### ISSUE THREAD

**Issue by slyedoc** [jakobhellermann/bevy-inspector-egui#25]
Is there a way to access InspectorWindows and say control when a window is open, currently forking and making it public, and adding want I need.  Am I missing something?

Still new to bevy and egui, and first time using bevy-inspector-egui.  Really a pleasure to use though =-)

**Comment by jakobhellermann** [comment]
I exposed the InspectorWindows now in the `main` branch, this is how you can control the visibility:
https://github.com/jakobhellermann/bevy-inspector-egui/blob/f73bd92968bdaf8fb0b6e017768038730942ba34/examples/hide_window.rs#L23-L24

I'll release a new version soon.

**Comment by slyedoc** [comment]
Huge thanks, love your work.

**Comment by AqilCont** [comment]
Sorry, to add to that, is there a way to control WorldInspector windows? I didn't find anything obvious from looking at the API.

**Comment by Rust-Ninja-Sabi** [comment]
Closing WorldInspector? Any suggestions?
