### ISSUE TITLE
Add Impl for UVecs?

### ISSUE THREAD

**Issue by jguhlin** [jakobhellermann/bevy-inspector-egui#26]
Per title. Happy to do it if you are good with a PR.

Cheers,
--Joseph

**Comment by jakobhellermann** [comment]
A PR would be appreciated. You can probably just do it like the Vec4 impl here: https://github.com/jakobhellermann/bevy-inspector-egui/blob/2a7a0c1f64fd311955d14b8384a42738d38debb8/src/impls/vec.rs#L168

**Comment by jakobhellermann** [comment]
Done: https://github.com/jakobhellermann/bevy-inspector-egui/commit/4c2e505d350a61f69c07d3e928a04fa48a865af4
