### ISSUE TITLE
Inspectable with vec of generic type

### ISSUE THREAD

**Issue by AnotherCoolDude** [jakobhellermann/bevy-inspector-egui#29]
Hey, 

thanks for the awesome crate!

Maybe you can help me with an issue I ran into: I have a resource `Table` which I want to inspect at runtime:

```rust 
#[derive(Inspectable)]
pub struct Table<T: Copy + Debug + Clone> {
    pub radius: Distance, 
    pub size: Distance,
    pub tiles: Vec<T>, 
}
``` 

`T` can be different types of Tiles, therefore it's generic. 

It keeps telling me `struct defined here, with 1 type parameter: "T"`

Is there a way to make the struct inspectable?

**Comment by jakobhellermann** [comment]
It should be fixed now with https://github.com/jakobhellermann/bevy-inspector-egui/commit/181d941abc79cbb458ef1e7b73bdd337733b1b5a, can you try if it works now for you?

You can depend on the git version using
```toml
bevy-inspector-egui = { git = "https://github.com/jakobhellermann/bevy-inspector-egui", branch = "main" }
```

**Comment by AnotherCoolDude** [comment]
Awesome, works like a charm. Thank you very much 👍
