### ISSUE TITLE
Linking Error

### ISSUE THREAD

**Issue by Circuit8** [jakobhellermann/bevy-inspector-egui#33]
Trying to run any of the examples gives me a linking error:

```
error: linking with `cc` failed: exit status: 1
...
 = note: /usr/bin/ld: cannot find -lxcb-render
          /usr/bin/ld: cannot find -lxcb-shape
          /usr/bin/ld: cannot find -lxcb-xfixes
          collect2: error: ld returned 1 exit status
```
I'm running on `Ubuntu 20.04.2 LTS`
Rust version `stable-x86_64-unknown-linux-gnu - rustc 1.54.0`

Thanks in advance for your help.

**Comment by jakobhellermann** [comment]
This looks like you're missing some native dependencies required by bevy.
Can you run the steps at https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md and try again?

**Comment by Circuit8** [comment]
Just double checked and I have everything installed, building and running the bevy examples, and my own bevy project works just fine. Seems to only occur with this project so far.

**Comment by Circuit8** [comment]
Further to this, checked on my other ubuntu device, still had the same issue. I did notice though the first time I attempt to build the project after adding the crate this comes up:

```
error: extern location for bevy_inspector_egui_derive does not exist: .../target/debug/deps/libbevy_inspector_egui_derive-10c1349a65bafbf5.so
  --> .../.cargo/registry/src/github.com-1ecc6299db9ec823/bevy-inspector-egui-0.5.1/src/lib.rs:90:9
   |
90 | pub use bevy_inspector_egui_derive::Inspectable;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `bevy-inspector-egui`
```

Further attempts to do `cargo build` result in the linking error from my first post.

**Comment by Circuit8** [comment]
FYI managed to fix this by installing `libxcb-composite0-dev`. Thanks for the great library, really appreciate it!
