### ISSUE TITLE
Troubles with Inspectable

### ISSUE THREAD

**Issue by korczis** [jakobhellermann/bevy-inspector-egui#35]
I am trying to integrate your branch with my code but I am getting following error.

Any idea how can I mitigate this?

Bonus question: Is WorldInspectorPlugin supposed to work?

```
    | #[derive(Inspectable)]
    |          ^^^^^^^^^^^
    |          |
    |          expected struct `bevy_app::app::App`, found struct `bevy::prelude::App`
    |          help: change the parameter type to match the trait: `&mut bevy_app::app::App`
    |
    = note: expected fn pointer `fn(&mut bevy_app::app::App)`
               found fn pointer `fn(&mut bevy::prelude::App)`
    = note: this error originates in the derive macro `Inspectable` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by jakobhellermann** [comment]
This error message usually occurs when using multiple versions of bevy.
What does `cargo tree -i bevy_app` print for you?

What isn't working for the WorldInspector? If it is shown but doesn't let you inspect custom components, you need to [`register`](https://docs.rs/bevy-inspector-egui/0.6.1/bevy_inspector_egui/world_inspector/struct.InspectableRegistry.html#method.register) them as [shown in the readme].
