### ISSUE TITLE
Demonstrate how to ignore fields in examples

### ISSUE THREAD

**Issue by alice-i-cecile** [jakobhellermann/bevy-inspector-egui#39]
From https://github.com/jakobhellermann/bevy-inspector-egui/blob/8c39d21a4783217d6d1589d74858530a53a94c54/tests/generics_bound.rs#L19, this feature already exists. However, it does not appear to be demonstrated in the examples, and is tricky for new users to discover.

A very simple dedicated example showing how and why to use this feature would be helpful!

**Comment by jakobhellermann** [comment]
I added an example showcasing the different attributes, thanks for the idea.
https://github.com/jakobhellermann/bevy-inspector-egui/blob/main/examples/attributes.rs

The other place where one might discover the attributes would be in the docs for `Inspectable`: https://docs.rs/bevy-inspector-egui/latest/bevy_inspector_egui/trait.Inspectable.html#default-attributes
