### ISSUE TITLE
Any way to make the inspector way toggleable with a keypress?

### ISSUE THREAD

**Issue by stevenliebregt** [jakobhellermann/bevy-inspector-egui#49]
Couldn't find any info on this, is it possible to toggle the window using a keypress?

**Comment by jakobhellermann** [comment]
If you're using the [world inspector](https://docs.rs/bevy-inspector-egui/latest/bevy_inspector_egui/struct.WorldInspectorParams.html), you can set the `enabled` boolean when a key is pressed in a system, something like
```rust
fn toggle_inspector(input: Res<Input<KeyCode>>, world_inspector_params: ResMut<WorldInspectorParams>) {
  if input.just_pressed(KeyCode::Escape) {
    world_inspector.params.enabled = !world_inspector_params.enabled;
  }
}
```

**Comment by stevenliebregt** [comment]
Brilliant! Thanks so much, I'm quite new to Bevy so I hadn't figured out that I could use that resource.
