### ISSUE TITLE
Make bevy_ui dependency optional

### ISSUE THREAD

**Issue by Shatur** [jakobhellermann/bevy-inspector-egui#52]
Currently bevy_ui is on a very early stage and most people use egui for ui.
So I suggest to make `bevy_ui` optional.

**Comment by jakobhellermann** [comment]
Yeah, currently `bevy-inspector-egui` unconditionally depends on `"bevy_render", "bevy_pbr", "bevy_sprite", "bevy_text", "bevy_ui"`. It makes sense to put those behind feature flags, but probably enabled by default.

I wish cargo had some concept of transitive features where `bevy-inspector-egui` could detect whether the user has features enabled on bevy and act accordingly, but default features should be good enough here.

Will implement this before the release updating to bevy 0.7 :+1:

**Comment by Shatur** [comment]
> It makes sense to put those behind feature flags, but probably enabled by default.

It would be great!

> Will implement this before the release updating to bevy 0.7 +1

Looking forward to it!

**Comment by jakobhellermann** [comment]
Done and released in 0.10
