### ISSUE TITLE
WorldInspector component sorting

### ISSUE THREAD

**Issue by DarkMara** [jakobhellermann/bevy-inspector-egui#6]
I think it would be useful to be able to sort the components when inspecting an entity with the WorldInspector. I think sorting by name would be a good default.

**Comment by jakobhellermann** [comment]
I can add that possibility, but I'm not sure I like it as a default. For example, without sorting the `Transform` and `GlobalTransform` are next to each other, with sorting they are not.

**Comment by DarkMara** [comment]
Yeah that's true. Once you get a lot of components though it gets difficult to use unless there is some kind of sorting. You can add it as a setting.

**Comment by jakobhellermann** [comment]
You can now 
```rust
app
    .insert_resource(WorldInspectorParams {
        sort_components: true,
        ..Default::default()
    })
    .add_plugin(WorldInspectorPlugin)
```
