### ISSUE TITLE
Vec2 inspector should show fields by default

### ISSUE THREAD

**Issue by DarkMara** [jakobhellermann/bevy-inspector-egui#7]
I noticed by default, the inspector for Vec2 shows a graph of some kind. It seems more useful to show the fields by default, like it does for Vec3. I think it'd be better to show the graph by marking a field with an attribute.

**Comment by jakobhellermann** [comment]
Done in the `bevy-0.5` branch. By default it now gets shown as two fields and you can get the old behaviour using `#[inspectable(visual)]`
