### ISSUE TITLE
Bevy 0.5

### ISSUE THREAD

**Issue by thorlucas** [jakobhellermann/bevy-inspector-egui#9]
Bevy 0.5 support

**Comment by jakobhellermann** [comment]
The `bevy-0.5` branch already supports the `main` version of bevy but I'm waiting on the release of [bevy_egui](https://github.com/mvlabat/bevy_egui/pull/12) to release a version to crates.io.

**Comment by jakobhellermann** [comment]
Version 0.4 with bevy 0.5 support is released
